export const DATA = [
   {
    id: '1',
    day: 'Monday',
    timeOfDay: 'evening',
    Kilometer: '12.05',
    avgPace: '12\'11"',
    time: '12:00',
    calories: 116,
    totalKmRan: '240',
   },
   {
    id: '2',
    day: 'Tuesday',
    timeOfDay: 'morning',
    Kilometer: '14.05',
    avgPace: '25\'11"',
    time: '4:00',
    calories: 116,
    totalKmRan: '460',
   },
   {
    id: '3',
    day: 'Wednesday',
    timeOfDay: 'Afternoon',
    Kilometer: '12.05',
    avgPace: '12\'11"',
    time: '12:00',
    calories: 116,
    totalKmRan: '600',
   },
   {
    id: '4',
    day: 'Monday',
    timeOfDay: 'evening',
    Kilometer: '12.05',
    avgPace: '12\'11"',
    time: '12:00',
    calories: 116,
    totalKmRan: '240',
   },
   {
    id: '5',
    day: 'Monday',
    timeOfDay: 'evening',
    Kilometer: '12.05',
    avgPace: '12\'11"',
    time: '12:00',
    calories: 116,
    totalKmRan: '240',
   },
   {
    id: '6',
    day: 'Monday',
    timeOfDay: 'evening',
    Kilometer: '12.05',
    avgPace: '12\'11"',
    time: '12:00',
    calories: 116,
    totalKmRan: '240',
   },
  ];

  //kilometer per level

  export const levels = [
   {id: 1, level: 'blue', kilometerRequired: 0},
   {id: 2, level: 'pink', kilometerRequired: 250},
   {id: 3, level: 'green', kilometerRequired: 450},
   {id: 4, level: 'orange', kilometerRequired: 600},
  ];