export const DATA = [
   {
    id: '1',
    day: 'Monday',
    timeOfDay: 'evening',
    Kilometer: '12.05',
    avgPace: '12\'11"',
    time: '12:00',
   },
   {
    id: '2',
    day: 'Monday',
    timeOfDay: 'evening',
    Kilometer: '12.05',
    avgPace: '12\'11"',
    time: '12:00',
   },
   {
    id: '3',
    day: 'Monday',
    timeOfDay: 'evening',
    Kilometer: '12.05',
    avgPace: '12\'11"',
    time: '12:00',
   },
   {
    id: '4',
    day: 'Monday',
    timeOfDay: 'evening',
    Kilometer: '12.05',
    avgPace: '12\'11"',
    time: '12:00',
   },
   {
    id: '5',
    day: 'Monday',
    timeOfDay: 'evening',
    Kilometer: '12.05',
    avgPace: '12\'11"',
    time: '12:00',
   },
   {
    id: '6',
    day: 'Monday',
    timeOfDay: 'evening',
    Kilometer: '12.05',
    avgPace: '12\'11"',
    time: '12:00',
   }
  ];